from enum import Enum


def get_enum_member_by_value(enum_cls, value):
    for member in enum_cls.__members__.values():
        if member.value == value:
            return member
    raise ValueError(f"No {enum_cls.__name__} member with value '{value}'")


class ChannelType(str, Enum):
    google = "google"
    facebook = "facebook"
    google_analytics = "google_analytics"
    sheets = "sheets"
    airpipe = "airpipe"
    youtube = "youtube"
    instagram_media = "instagram_media"
    instagram_account = "instagram_account"


class FieldType(str, Enum):
    metric = "metric"
    dimension = "dimension"


class OnboardingStage(str, Enum):
    signed_up = "signed_up"
    connected = "connected"
    data_added = "data_added"


class Environment(str, Enum):
    production = "production"
    development = "development"


class LookerFieldType(str, Enum):
    text = "TEXT"
    number = "NUMBER"
    date = "YEAR_MONTH_DAY"
    boolean = "BOOLEAN"


class JoinType(str, Enum):
    inner = "INNER JOIN"
    left = "LEFT JOIN"
    right = "RIGHT JOIN"
    full = "FULL OUTER JOIN"


class UserRoleType(str, Enum):
    agency = "Agency Owner / Founder"
    b2b = "B2B Marketer"
    technical = "Technical Marketer"
    performance = "Performance Marketer"
    seo = "SEO Marketer"
    content = "Content Marketer"
    data = "Data Engineer / Analyst / Scientist"
    software = "Software Engineer"
    other = "Other"

facebook_metrics = [
    {
        "value": "clicks",
        "label": "Clicks",
        "alt_value": "facebook_clicks",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "conversions",
        "label": "Conversions",
        "alt_value": "facebook_conversions",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "cost_per_conversion",
        "label": "Cost Per Conversion",
        "alt_value": "facebook_cost_per_conversion",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "cpc",
        "label": "CPC",
        "alt_value": "facebook_cpc",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "cpm",
        "label": "CPM",
        "alt_value": "facebook_cpm",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "cpp",
        "label": "CPP",
        "alt_value": "facebook_cpp",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "ctr",
        "label": "CTR",
        "alt_value": "facebook_ctr",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "frequency",
        "label": "Frequency",
        "alt_value": "facebook_frequency",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "impressions",
        "label": "Impressions",
        "alt_value": "facebook_impressions",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "reach",
        "label": "Reach",
        "alt_value": "facebook_reach",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "spend",
        "label": "Spend",
        "alt_value": "facebook_spend",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    # {
    #     "value": "video_avg_time_watched_actions",
    #     "label": "Video Avg Time Watched Actions",
    #     "alt_value": "facebook_video_avg_time_watched_actions",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.facebook,
    #     "img": "facebook-icon",
    #     "default": True,
    # },
    {
        "value": "video_p25_watched_actions",
        "label": "Views 25% Video Completion",
        "alt_value": "facebook_25_percent_completion",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "video_p50_watched_actions",
        "label": "Views 50% Video Completion",
        "alt_value": "facebook_50_percent_completion",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "video_p75_watched_actions",
        "label": "Views 75% Video Completion",
        "alt_value": "facebook_75_percent_completion",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "video_p95_watched_actions",
        "label": "Views 95% Video Completion",
        "alt_value": "facebook_95_percent_completion",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "video_p100_watched_actions",
        "label": "Views 100% Video Completion",
        "alt_value": "facebook_100_percent_completion",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "cost_per_thruplay",
        "label": "Cost per Thruplay",
        "alt_value": "facebook_cost_per_thruplay",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    # {
    #     "value": "video_time_watched_actions",
    #     "label": "Video Time Watched Actions",
    #     "alt_value": "facebook_video_time_watched_actions",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.facebook,
    #     "img": "facebook-icon",
    #     "default": True,
    # }
    {
        "value": "video_view",
        "label": "3 Second Video View",
        "alt_value": "facebook_three_second_video_view",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "post",
        "label": "Post Shares",
        "alt_value": "facebook_post_shares",
        "type": FieldType.metric,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    }
]

facebook_dimensions = [
    {
        "value": "account_id",
        "label": "Account Id",
        "alt_value": "facebook_account_id",
        "type": FieldType.dimension,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "account_name",
        "label": "Account Name",
        "alt_value": "facebook_account_name",
        "type": FieldType.dimension,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "adset_id",
        "label": "Adset Id",
        "alt_value": "facebook_adset_id",
        "type": FieldType.dimension,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "adset_name",
        "label": "Adset Name",
        "alt_value": "facebook_adset_name",
        "type": FieldType.dimension,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "campaign_id",
        "label": "Campaign Id",
        "alt_value": "facebook_campaign_id",
        "type": FieldType.dimension,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "campaign_name",
        "label": "Campaign Name",
        "alt_value": "facebook_campaign_name",
        "type": FieldType.dimension,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
        "default": False,
    },
    {
        "value": "ad_id",
        "label": "Ad Id",
        "alt_value": "facebook_ad_id",
        "type": FieldType.dimension,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": False,
    },
    {
        "value": "ad_name",
        "label": "Ad Name",
        "alt_value": "facebook_ad_name",
        "type": FieldType.dimension,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
    {
        "value": "date",
        "label": "Date",
        "alt_value": "facebook_date",
        "type": FieldType.dimension,
        "channel": ChannelType.facebook,
        "img": "facebook-icon",
        "default": True,
    },
]

google_metrics = [
    {
        "value": "metrics.average_cpc",
        "label": "CPC",
        "alt_value": "google_cpc",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": False,
    },
    {
        "value": "metrics.average_cpe",
        "label": "CPE",
        "alt_value": "google_cpe",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": False,
    },
    {
        "value": "metrics.average_cpm",
        "label": "CPM",
        "alt_value": "google_cpm",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": False,
    },
    {
        "value": "metrics.average_cpv",
        "label": "CPV",
        "alt_value": "google_cpv",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": False,
    },
    {
        "value": "metrics.clicks",
        "label": "Clicks",
        "alt_value": "google_clicks",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": True,
    },
    {
        "value": "metrics.conversions",
        "label": "Conversions",
        "alt_value": "google_conversions",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": True,
    },
    {
        "value": "metrics.cost_micros",
        "label": "Spend",
        "alt_value": "google_spend",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": True,
    },
    {
        "value": "metrics.cost_per_conversion",
        "label": "Cost Per Conversion",
        "alt_value": "google_cost_per_conversion",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": False,
    },
    {
        "value": "metrics.engagements",
        "label": "Engagements",
        "alt_value": "google_engagements",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": False,
    },
    {
        "value": "metrics.impressions",
        "label": "Impressions",
        "alt_value": "google_impressions",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": True,
    },
    {
        "value": "metrics.interactions",
        "label": "Interactions",
        "alt_value": "google_interactions",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": False,
    },
    # {
    #     "value": "metrics.search_impression_share",
    #     "label": "Search Impression Share",
    #     "alt_value": "google_search_impression_share",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.google,
    #     "img": "google-ads-icon",
    #     "default": True,
    # },
    {
       "value": "metrics.ctr",
       "label": "CTR",
       "alt_value": "google_ctr",
       "type": FieldType.metric,
       "channel": ChannelType.google,
       "img": "google-ads-icon",
       "default": True 
    },
    {
        "value": "metrics.top_impression_percentage",
        "label": "Top Impression Percentage",
        "alt_value": "google_top_impression_percentage",
        "type": FieldType.metric,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": True,
    },
]

google_dimensions = [
    {
        "value": "ad_group_ad.ad.id",
        "label": "Ad Id",
        "type": FieldType.dimension,
        "channel": ChannelType.google,
        "alt_value": "google_ad_id",
        "img": "google-ads-icon",
        "default": False,
    },
    {
        "value": "ad_group_ad.ad.name",
        "label": "Ad Name",
        "type": FieldType.dimension,
        "channel": ChannelType.google,
        "alt_value": "google_ad_name",
        "img": "google-ads-icon",
        "default": True,
    },
    {
        "value": "ad_group.name",
        "label": "Ad Group Name",
        "type": FieldType.dimension,
        "channel": ChannelType.google,
        "alt_value": "google_ad_group_name",
        "img": "google-ads-icon",
        "default": True,
    },
    {
        "value": "ad_group.id",
        "label": "Ad Group Id",
        "alt_value": "google_ad_group_id",
        "type": FieldType.dimension,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": False,
    },
    {
        "value": "campaign.id",
        "label": "Campaign Id",
        "alt_value": "google_campaign_id",
        "type": FieldType.dimension,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": False,
    },
    {
        "value": "campaign.name",
        "label": "Campaign Name",
        "alt_value": "google_campaign_name",
        "type": FieldType.dimension,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": True,
    },
    {
        "value": "segments.keyword.info.text",
        "label": "Keyword Text",
        "alt_value": "google_keyword_text",
        "type": FieldType.dimension,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": True,
    },
    {
        "value": "segments.date",
        "label": "Date",
        "alt_value": "google_date",
        "type": FieldType.dimension,
        "channel": ChannelType.google,
        "img": "google-ads-icon",
        "default": True,
    },
]

google_analytics_metrics = [
    {
        "value": "totalUsers",
        "label": "Total Users",
        "alt_value": "google_analytics_users",
        "type": FieldType.metric,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": True,
    },
    {
        "value": "newUsers",
        "label": "New Users",
        "alt_value": "google_analytics_new_users",
        "type": FieldType.metric,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": False,
    },
    {
        "value": "activeUsers",
        "label": "Active Users",
        "alt_value": "google_analytics_active_Users",
        "type": FieldType.metric,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": False,
    },
    {
        "value": "sessions",
        "label": "Sessions",
        "alt_value": "google_analytics_sessions",
        "type": FieldType.metric,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": True,
    },
    {
        "value": "transactions",
        "label": "Transactions",
        "alt_value": "google_analytics_transactions",
        "type": FieldType.metric,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": False,
    },
    {
        "value": "checkouts",
        "label": "Checkouts",
        "alt_value": "google_analytics_checkouts",
        "type": FieldType.metric,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": False,
    },
    {
        "value": "conversions",
        "label": "Conversions",
        "alt_value": "google_analytics_conversions",
        "type": FieldType.metric,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": True,
    },
]


# Define the data as Python objects
google_analytics_dimensions = [
    {
        "value": "browser",
        "label": "Browser",
        "alt_value": "google_analytics_browser",
        "type": FieldType.dimension,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": False,
    },
    {
        "value": "city",
        "label": "City",
        "alt_value": "google_analytics_city",
        "type": FieldType.dimension,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": False,
    },
    {
        "value": "continent",
        "label": "Continent",
        "alt_value": "google_analytics_continent",
        "type": FieldType.dimension,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": False,
    },
    {
        "value": "country",
        "label": "Country",
        "alt_value": "google_analytics_country",
        "type": FieldType.dimension,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": False,
    },
    {
        "value": "eventName",
        "label": "Event Name",
        "alt_value": "google_analytics_event_Name",
        "type": FieldType.dimension,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": True,
    },
    {
        "value": "deviceCategory",
        "label": "Device Category",
        "alt_value": "google_analytics_device_Category",
        "type": FieldType.dimension,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": False,
    },
    # {
    #     "value": "medium",
    #     "label": "Medium",
    #     "alt_value": "google_analytics_medium",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.google_analytics,
    #     "img": "google-analytics-icon",
    #     "default": False,
    # },
    # {
    #     "value": "source",
    #     "label": "Source",
    #     "alt_value": "google_analytics_source",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.google_analytics,
    #     "img": "google-analytics-icon",
    #     "default": False,
    # },
    {
        "value": "date",
        "label": "Date",
        "alt_value": "google_analytics_date",
        "type": FieldType.dimension,
        "channel": ChannelType.google_analytics,
        "img": "google-analytics-icon",
        "default": True,
    },
]

youtube_metrics = [
    {
        "value": "views",
        "label": "Views",
        "alt_value": "youtube_views",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    {
        "value": "adImpressions",
        "label": "Ad Impressions",
        "alt_value": "youtube_ad_impressions",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
        {
        "value": "cpm",
        "label": "CPM",
        "alt_value": "youtube_cpm",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "averageViewDuration",
        "label": "Average View Duration",
        "alt_value": "youtube_average_view_duration",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    {
        "value": "averageViewPercentage",
        "label": "Average View Percentage",
        "alt_value": "youtube_average_view_percentage",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    {
        "value": "estimatedMinutesWatched",
        "label": "Estimated Minutes Watched",
        "alt_value": "youtube_estimated_minutes_watched",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    # {
    #     "value": "redViews",
    #     "label": "Premium Views",
    #     "alt_value": "youtube_premium_views",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "viewerPercentage",
    #     "label": "Logged In Viewer Percentage",
    #     "alt_value": "youtube_logged_in_viewer_percentage",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "estimatedRedMinutesWatched",
    #     "label": "Estimated Premium Minutes Watched",
    #     "alt_value": "youtube_estimated_premium_minutes_watched",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    {
        "value": "comments",
        "label": "Comments",
        "alt_value": "youtube_comments",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    {
        "value": "shares",
        "label": "Shares",
        "alt_value": "youtube_shares",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    {
        "value": "likes",
        "label": "Likes",
        "alt_value": "youtube_likes",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    {
        "value": "dislikes",
        "label": "Dislikes",
        "alt_value": "youtube_dislikes",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    {
        "value": "subscribersGained",
        "label": "Subscribers Gained",
        "alt_value": "youtube_subscribers_gained",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    {
        "value": "subscribersLost",
        "label": "Subscribers Lost",
        "alt_value": "youtube_subscribers_lost",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    {
        "value": "videosAddedToPlaylists",
        "label": "Videos Added To Playlists",
        "alt_value": "youtube_videos_added_to_playlists",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "videosRemovedFromPlaylists",
        "label": "Videos Removed From Playlists",
        "alt_value": "youtube_videos_removed_from_playlists",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },    {
        "value": "annotationImpressions",
        "label": "Annotation Impressions",
        "alt_value": "youtube_annotation_impressions",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "annotationClickableImpressions",
        "label": "Annotation Clickable Impressions",
        "alt_value": "youtube_annotation_clickable_impressions",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "annotationClicks",
        "label": "Annotation Clicks",
        "alt_value": "youtube_annotation_clicks",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "annotationClickThroughRate",
        "label": "Annotation Click-Through Rate",
        "alt_value": "youtube_annotation_click_through_rate",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "annotationClosableImpressions",
        "label": "Annotation Closable Impressions",
        "alt_value": "youtube_annotation_closable_impressions",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "annotationCloses",
        "label": "Annotation Closes",
        "alt_value": "youtube_annotation_closes",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "annotationCloseRate",
        "label": "Annotation Close Rate",
        "alt_value": "youtube_annotation_close_rate",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
{
        "value": "cardImpressions",
        "label": "Card Impressions",
        "alt_value": "youtube_card_impressions",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "cardClicks",
        "label": "Card Clicks",
        "alt_value": "youtube_card_clicks",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "cardClickRate",
        "label": "Card Click Rate",
        "alt_value": "youtube_card_click_rate",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "cardTeaserImpressions",
        "label": "Card Teaser Impressions",
        "alt_value": "youtube_card_teaser_impressions",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "cardTeaserClicks",
        "label": "Card Teaser Clicks",
        "alt_value": "youtube_card_teaser_clicks",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "cardTeaserClickRate",
        "label": "Card Teaser Click Rate",
        "alt_value": "youtube_card_teaser_click_rate",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    #  {
    #     "value": "audienceWatchRatio",
    #     "label": "Audience Watch Ratio",
    #     "alt_value": "youtube_audience_watch_ratio",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "relativeRetentionPerformance",
    #     "label": "Relative Retention Performance",
    #     "alt_value": "youtube_relative_retention_performance",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "estimatedRevenue",
    #     "label": "Estimated Revenue",
    #     "alt_value": "youtube_estimated_revenue",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    {
        "value": "estimatedAdRevenue",
        "label": "Estimated Ad Revenue",
        "alt_value": "youtube_estimated_ad_revenue",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    # {
    #     "value": "estimatedRedPartnerRevenue",
    #     "label": "Estimated Red Partner Revenue",
    #     "alt_value": "youtube_estimated_red_partner_revenue",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    {
        "value": "grossRevenue",
        "label": "Gross Revenue",
        "alt_value": "youtube_gross_revenue",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "monetizedPlaybacks",
        "label": "Monetized Playbacks",
        "alt_value": "youtube_monetized_playbacks",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    },
    {
        "value": "playbackBasedCpm",
        "label": "Playback-Based CPM",
        "alt_value": "youtube_playback_based_cpm",
        "type": FieldType.metric,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": False,
    }
]

youtube_dimensions = [
    {
        "value": "day",
        "label": "Date",
        "alt_value": "youtube_date",
        "type": FieldType.dimension,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
#    {
#         "value": "video",
#         "label": "Video Id",
#         "alt_value": "youtube_video_id",
#         "type": FieldType.dimension,
#         "channel": ChannelType.youtube,
#         "img": "youtube-icon",
#         "default": True,
#     },
    # {
    #     "value": "playlist",
    #     "label": "Playlist",
    #     "alt_value": "youtube_playlist",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    {
        "value": "channel",
        "label": "Channel",
        "alt_value": "youtube_channel",
        "type": FieldType.dimension,
        "channel": ChannelType.youtube,
        "img": "youtube-icon",
        "default": True,
    },
    # {
    #     "value": "country",
    #     "label": "Country",
    #     "alt_value": "youtube_country",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "province",
    #     "label": "Province",
    #     "alt_value": "youtube_province",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "city",
    #     "label": "City",
    #     "alt_value": "youtube_city",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "insightPlaybackLocationType",
    #     "label": "Insight Playback Location Type",
    #     "alt_value": "youtube_insight_playback_location_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "insightPlaybackLocationDetail",
    #     "label": "Insight Playback Location Detail",
    #     "alt_value": "youtube_insight_playback_location_detail",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "creatorContentType",
    #     "label": "Creator Content Type",
    #     "alt_value": "youtube_creator_content_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "liveOrOnDemand",
    #     "label": "Live or On-Demand",
    #     "alt_value": "youtube_live_or_on_demand",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "subscribedStatus",
    #     "label": "Subscribed Status",
    #     "alt_value": "youtube_subscribed_status",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "youtubeProduct",
    #     "label": "YouTube Product",
    #     "alt_value": "youtube_product",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "insightTrafficSourceType",
    #     "label": "Insight Traffic Source Type",
    #     "alt_value": "youtube_insight_traffic_source_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "insightTrafficSourceDetail",
    #     "label": "Insight Traffic Source Detail",
    #     "alt_value": "youtube_insight_traffic_source_detail",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "deviceType",
    #     "label": "Device Type",
    #     "alt_value": "youtube_device_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "operatingSystem",
    #     "label": "Operating System",
    #     "alt_value": "youtube_operating_system",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "ageGroup",
    #     "label": "Age Group",
    #     "alt_value": "youtube_age_group",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "gender",
    #     "label": "Gender",
    #     "alt_value": "youtube_gender",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "sharingService",
    #     "label": "Sharing Service",
    #     "alt_value": "youtube_sharing_service",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "elapsedVideoTimeRatio",
    #     "label": "Elapsed Video Time Ratio",
    #     "alt_value": "youtube_elapsed_video_time_ratio",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "audienceType",
    #     "label": "Audience Type",
    #     "alt_value": "youtube_audience_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # },
    # {
    #     "value": "adType",
    #     "label": "Ad Type",
    #     "alt_value": "youtube_ad_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.youtube,
    #     "img": "youtube-icon",
    #     "default": False,
    # }
]

instagram_account_metrics = [
    {
        "value": "impressions",
        "label": "Impressions",
        "alt_value": "instagram_account_impressions",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": True,
    },
{
        "value": "email_contacts",
        "label": "Email Contacts",
        "alt_value": "instagram_account_email_contacts",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": False,
    },
    {
        "value": "follower_count",
        "label": "Follower Count",
        "alt_value": "instagram_account_follower_count",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": False,
    },
    {
        "value": "get_directions_clicks",
        "label": "Get Directions Clicks",
        "alt_value": "instagram_account_get_directions_clicks",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": False,
    },
    # {
    #     "value": "online_followers",
    #     "label": "Online Followers",
    #     "alt_value": "instagram_account_online_followers",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.instagram_account,
    #     "img": "instagram-icon",
    #     "default": False,
    # },
    {
        "value": "phone_call_clicks",
        "label": "Phone Call Clicks",
        "alt_value": "instagram_account_phone_call_clicks",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": False,
    },
    {
        "value": "profile_views",
        "label": "Profile Views",
        "alt_value": "instagram_account_profile_views",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": False,
    },
    {
        "value": "reach",
        "label": "Reach",
        "alt_value": "instagram_account_reach",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "text_message_clicks",
        "label": "Text Message Clicks",
        "alt_value": "instagram_account_text_message_clicks",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": False,
    },
    {
        "value": "website_clicks",
        "label": "Website Clicks",
        "alt_value": "instagram_account_website_clicks",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": False,
    }

]

instagram_account_dimensions = [
    {
        "value": "date",
        "label": "Date",
        "alt_value": "instagram_date",
        "type": FieldType.dimension,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": True
    },
    {
        "value": "id",
        "label": "Account Id",
        "alt_value": "instagram_account_id",
        "type": FieldType.dimension,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": True
    },
    {
        "value": "name",
        "label": "Account Name",
        "alt_value": "instagram_account_name",
        "type": FieldType.dimension,
        "channel": ChannelType.instagram_account,
        "img": "instagram-icon",
        "default": True
    }
    # {
    #     "value": "media_product_type",
    #     "label": "Media Product Type",
    #     "alt_value": "instagram_account_media_product_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.instagram_account,
    #     "img": "instagram-icon",
    #     "default": True,
    # },
    # {
    #    "value": "follow_type",
    #     "label": "Follow Type",
    #     "alt_value": "instagram_account_follow_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.instagram_account,
    #     "img": "instagram-icon",
    #     "default": False,
    # },
    # {
    #     "value": "contact_button_type",
    #     "label": "Contact Button Type",
    #     "alt_value": "instagram_account_contact_button_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.instagram_account,
    #     "img": "instagram-icon",
    #     "default": False,
    # }
]

instagram_media_metrics = [
    {
        "value": "impressions",
        "label": "Impressions",
        "alt_value": "instagram_media_impressions",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "reach",
        "label": "Reach",
        "alt_value": "instagram_media_reach",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "saved",
        "label": "Saved",
        "alt_value": "instagram_media_saved",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "video_views",
        "label": "Video Views",
        "alt_value": "instagram_media_video_views",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "comments",
        "label": "Comments",
        "alt_value": "instagram_media_comments",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "ig_reels_avg_watch_time",
        "label": "Reels Average Watch Time",
        "alt_value": "instagram_media_ig_reels_avg_watch_time",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": False,
    },
    {
        "value": "ig_reels_video_view_total_time",
        "label": "Reels Total View Time",
        "alt_value": "instagram_media_ig_reels_video_view_total_time",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": False,
    },
    {
        "value": "likes",
        "label": "Likes",
        "alt_value": "instagram_media_likes",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "plays",
        "label": "Plays",
        "alt_value": "instagram_media_plays",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": False,
    },
    {
        "value": "shares",
        "label": "Shares",
        "alt_value": "instagram_media_shares",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "total_interactions",
        "label": "Total Interactions",
        "alt_value": "instagram_media_total_interactions",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "replies",
        "label": "Replies",
        "alt_value": "instagram_media_replies",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "follows",
        "label": "Follows",
        "alt_value": "instagram_media_follows",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "profile_activity",
        "label": "Profile Activity",
        "alt_value": "instagram_media_profile_activity",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": False,
    },
    {
        "value": "profile_visits",
        "label": "Profile Visits",
        "alt_value": "instagram_media_profile_visits",
        "type": FieldType.metric,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    # {
    #     "value": "navigation",
    #     "label": "Navigation",
    #     "alt_value": "instagram_media_navigation",
    #     "type": FieldType.metric,
    #     "channel": ChannelType.instagram_media,
    #     "img": "instagram-icon",
    #     "default": False,
    
    # }
]

instagram_media_dimensions = [
    {
        "value": "date",
        "label": "Date",
        "alt_value": "instagram_date",
        "type": FieldType.dimension,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "id",
        "label": "Media Id",
        "alt_value": "instagram_media_id",
        "type": FieldType.dimension,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "caption",
        "label": "Caption",
        "alt_value": "instagram_media_caption",
        "type": FieldType.dimension,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "media_url",
        "label": "Media URL",
        "alt_value": "instagram_media_url",
        "type": FieldType.dimension,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
        {
        "value": "owner",
        "label": "Owner",
        "alt_value": "instagram_media_owner",
        "type": FieldType.dimension,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    },
    {
        "value": "username",
        "label": "Username",
        "alt_value": "instagram_media_username",
        "type": FieldType.dimension,
        "channel": ChannelType.instagram_media,
        "img": "instagram-icon",
        "default": True,
    }
    # {
    #     "value": "media_product_type",
    #     "label": "Media Product Type",
    #     "alt_value": "instagram_media_product_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.instagram_media,
    #     "img": "instagram-icon",
    #     "default": True,
    # },
    # {
    #     "value": "media_type",
    #     "label": "Media Type",
    #     "alt_value": "instagram_media_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.instagram_media,
    #     "img": "instagram-icon",
    #     "default": True,
    # }
    # {
    #     "value": "action_type",
    #     "label": "Action Type",
    #     "alt_value": "instagram_action_type",
    #     "type": FieldType.dimension,
    #     "channel": ChannelType.instagram_media,
    #     "img": "instagram-icon",
    #     "default": True,
    # }
]